export default {
    GET_COLLECTIONS: 'GET_COLLECTIONS',

    GET_COLLECTIONS_REQUEST: 'GET_COLLECTIONS_REQUEST',
    GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS',
    GET_COLLECTIONS_FAIL: 'GET_COLLECTIONS_FAIL',
}